### ISSUE TITLE
Dependencies issues

### ISSUE THREAD

**Issue by undjike** [laravel-notification-channels/aws-sns#17]
To be able to install the package on **Laravel 8.40**, it's needed to:

- Downgrade guzzlehttp/psr7 from 2.0.0 to 1.8.2
- Remove psr/http-factory

Installation failed unless you do that. I had to execute
```
composer require laravel-notification-channel/aws-sns -with-all-dependencies
```
 for it to work (by performing these 2 actions automatically)

**Comment by claudsonm** [comment]
Will take a look at this when I have the time.

In the mean time, PRs fixing the issue are also welcome.

**Comment by claudsonm** [comment]
After a long while, I've addressed the issue. Huge thanks for pointing it out.

The problem resides in `aws-sdk-php`. They support `guzzlehttp/guzzle` 7.x,  but not the `guzzlehttp/ps7` 2.x.  The problem is affecting a lot of other packages, including things on the Laravel ecosystem such as Laravel Vapor.

Maintainers of the AWS SDK are already digging into it. As we can follow here: https://github.com/aws/aws-sdk-php/issues/2264

For now, I will let composer solve the conflict of dependencies, and just update the docs to instruct people to install this package using the `--update-with-dependencies` flag.
