### ISSUE TITLE
routeNotificationForSns not working for different field name

### ISSUE THREAD

**Issue by Zubair-Iftikhar** [laravel-notification-channels/aws-sns#19]
routeNotificationForSns is not working.. in User Model..
if then db field is phone then it's working fine..  but what if field name other?

```
    public function routeNotificationForSns($notification)
    {
        return $notification->mobileNumber;
    }
```

**Comment by claudsonm** [comment]
Yes, its in the user model, but the code you posted is wrong. It's not `return $notification->mobileNumber;`, it should be `return $this->mobileNumber;`

If you already fixed this, and is not working yet, this issue here can help you debug what's happening: https://github.com/laravel-notification-channels/aws-sns/issues/9
